name: Build Gamer Salon OS

on:
  schedule:
    - cron: '0 0 * * 0' # Compilation automatique chaque dimanche
  workflow_dispatch: # Permet de lancer la compilation à la main

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Image
        uses: redhat-actions/buildah-build@v2
        id: build-image
        with:
          image: gamer-salon-os
          tags: latest
          containerfiles: |
            ./Containerfile

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
